language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm-nightly

script:
  - phpunit --coverage-text
  - phpunit --group unicode --coverage-text

matrix:
  allow_failures:
    - php: hhvm-nightly
  fast_finish: true
